service: aws-fsharp2-1

provider:
  name: aws
  runtime: dotnetcore2.1

package:
  artifact: bin/release/netcoreapp2.1/publish/deploy-package.zip

functions:
  hello:
    handler: FsharpHandlers::AwsDotnetFsharp.Handler::hello
    events:
      - http:
          path: /
          method: get